# Site settings
title: Monthly Mix
email: mail@sammorrisdesign.co.uk
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.monthly.mx" # the base hostname & protocol for your site
permalink: /:year/:title/

# Build settings
highlighter: true
markdown: kramdown
sass:
  style: compressed
assets:
  compress:
    js: true
  prefix: "assets/js"
  sources:
    - _js

# Imports
gems:
  - octopress-autoprefixer
  - jekyll-assets